import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { City } from 'src/app/shared/models/City';

@Injectable({
  providedIn: 'root'
})
export class CityService {

  constructor() { }
  getAll():Observable<City[]>{
    const cities: City[] = [
      {
        id:1,
        name:"Akkaraipattu"
      },
      {
        id:2,
        name:"Ambalangoda"
      },
      {
        id:3,
        name:"Ampara"
      },
      {
        id:4,
        name:"Badulla"
      },
      {
        id:5,
        name:"Balangoda"
      },
      {
        id:6,
        name:"Bandarawela"
      },
      {
        id:7,
        name:"Batticaloa"
      },
      {
        id:8,
        name:"Beruwala"
      },
      {
        id:9,
        name:"Boralesgamuwa"
      },
      {
        id:10,
        name:"Chavakachcheri"
      },
      {
        id:11,
        name:"Chilaw"
      },
      {
        id:12,
        name:"Colombo"
      },
      {
        id:13,
        name:"Dambulla"
      },
      {
        id:14,
        name:"Dehiwala-Mount Lavinia"
      },
      {
        id:15,
        name:"Embilipitiya"
      },
      {
        id:16,
        name:"Eravur"
      },
      {
        id:17,
        name:"Galle"
      },
      {
        id:18,
        name:"Gampaha"
      },
      {
        id:19,
        name:"Gampola"
      },
      {
        id:20,
        name:"Hambantota"
      },
      {
        id:21,
        name:"Haputale"
      },
      {
        id:22,
        name:"Hatton-Dickoya"
      },
      {
        id:23,
        name:"Hikkaduwa"
      },
      {
        id:24,
        name:"Horana"
      },
      {
        id:25,
        name:"Ja-Ela"
      },
      {
        id:26,
        name:"Jaffna"
      },
      {
        id:27,
        name:"Kadugannawa"
      },
      {
        id:28,
        name:"Kaduwela"
      },
      {
        id:29,
        name:"Kalmuai"
      },
      {
        id:30,
        name:"Kalutara"
      },
      {
        id:31,
        name:"Kandy"
      },
      {
        id:32,
        name:"Kattankudy"
      },
      {
        id:33,
        name:"Katunayake"
      },
      {
        id:34,
        name:"Kegalle"
      },
      {
        id:35,
        name:"Kesbewa"
      },
      {
        id:36,
        name:"kilinochchi"
      },
      {
        id:37,
        name:"Kinniya"
      },
      {
        id:38,
        name:"Kolonnawa"
      },
      {
        id:38,
        name:"Kuliyapitiya"
      },
      {
        id:39,
        name:"Kurunegala"
      },
      {
        id:40,
        name:"Maharagama"
      },
      {
        id:41,
        name:"Mannar"
      },
      {
        id:42,
        name:"Matale"
      },
      {
        id:43,
        name:"Matara"
      },
      {
        id:44,
        name:"Minuwangoda"
      },
      {
        id:45,
        name:"Moneragala"
      },
      {
        id:46,
        name:"Moratuwa"
      },
      {
        id:47,
        name:"Mullaitivu"
      },
      {
        id:48,
        name:"Nawalapitiya"
      },
      {
        id:49,
        name:"Negombo"
      },
      {
        id:50,
        name:"Nuwara Eliya"
      },
      {
        id:51,
        name:"Panadura"
      },
      {
        id:52,
        name:"Peliyagoda"
      },
      {
        id:53,
        name:"Point Pedro"
      },
      {
        id:54,
        name:"Plonnaruwa"
      },
      {
        id:55,
        name:"Puttalam"
      },
      {
        id:56,
        name:"Ratnapura"
      },
      {
        id:57,
        name:"Avissawella"
      },
      {
        id:58,
        name:"Sri Jayawardenepura"
      },
      {
        id:59,
        name:"Tangalle"
      },
      {
        id:60,
        name:"Thalawakele"
      },
      {
        id:61,
        name:"Trincomalee"
      },
      {
        id:62,
        name:"Valvettithurai"
      },
      {
        id:63,
        name:"Vavniya"
      },
      {
        id:64,
        name:"Wattala-Mabole"
      },
      {
        id:65,
        name:"Wattegama"
      },
      {
        id:66,
        name:"Weligama"
      }
    ]

    return of(cities)
  }
}
